#!/bin/bash
# -e if error happen , exit immediately
# -u if unassigned argu exist , exit immediately
set -eu
path=$PWD # path in the time executing
RED="\033[31m"
BLUE="\033[34m"
GREEN="\033[32m"
AMARANTH='\033[35m'
DFT="\033[0m" # default

ERR="${RED}[!]${DFT}"
NOTE="${BLUE}[*]${DFT}"
INFO="${GREEN}[+]${DFT}"

if [ $# -ne 1 ]; then
    echo -e "${ERR} must provide a argument"
    exit 1
fi

valid_list=("run" "menu@todo" "recompile@todo" "ctf@todo" "clean")
if [[ ! " ${valid_list[@]} " =~ " $1 " ]]; then
    
    exit 1
fi


case "$1" in
    run)
        echo -e "${INFO} run the kernel build procedure"
        python3 main.py
        ;;
    menu@todo)
        echo "Executing command for 'menu@todo'"
        # Run the command for 'menu@todo'
        ;;
    recompile@todo)
        echo "Executing command for 'recompile@todo'"
        # Run the command for 'recompile@todo'
        ;;
    ctf@todo)
        echo "Executing command for 'ctf@todo'"
        # Run the command for 'ctf@todo'
        ;;
    clean)
        echo "Executing command for 'clean'"
        rm -rf fs-root
        rm -rf kernel-root
        rm -rf download
        ;;
    *)
        echo -e "${ERR} argu \`$1\` must in ${valid_list[*]}"
        exit 1
        ;;
esac