#!/bin/bash
# -e if error happen , exit immediately
# -u if unassigned argu exist , exit immediately
set -eu
path=$PWD # path in the time executing
RED="\033[31m"
BLUE="\033[34m"
GREEN="\033[32m"
AMARANTH='\033[35m'
DFT="\033[0m" # default

ERR="${RED}[!]${DFT}"
NOTE="${BLUE}[*]${DFT}"
INFO="${GREEN}[+]${DFT}"

if [ $# -le 1 ] || [ $# -gt 3 ]; then
    echo -e "${ERR} Usage : ./akd <option> [extra]"
    exit 1
fi

export PYTHONPATH=`pwd`

case "$1" in
    run)
        echo -e "${INFO} run the kernel build procedure"
        python3 main.py run
        ;;
    build)
        echo -e "${ERR} TODO"
        exit 1
        # python3 main.py run
        ;;
    menu@todo)
        echo "Executing command for 'menu@todo'"
        # Run the command for 'menu@todo'
        ;;
    recompile@todo)
        echo "Executing command for 'recompile@todo'"
        # Run the command for 'recompile@todo'
        ;;
    ctf)
        echo -e "${INFO} run the ctf kernel"
        python3 main.py $@
        ;;
    clean)
        echo "Executing command for 'clean'"
        rm -rf fs-root
        rm -rf kernel-root
        rm -rf download
        ;;
    *)
        echo -e "${ERR} argu \`$1\` must in ${valid_list[*]}"
        exit 1
        ;;
esac